# Generated by Django 4.1.7 on 2023-03-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0003_gamerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelist',
            name='moves',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamelist',
            name='turn',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
