# Generated by Django 4.1.7 on 2023-03-23 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friend', '0004_gamelist_moves_gamelist_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelist',
            name='black',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='b', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamelist',
            name='white',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='w', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
