# Generated by Django 4.1.7 on 2023-03-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0005_gamelist_black_gamelist_white'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='turn',
            field=models.IntegerField(null=True),
        ),
    ]
