# Generated by Django 4.1.7 on 2023-03-23 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friend', '0006_alter_gamelist_turn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='black',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='games',
            field=models.ManyToManyField(blank=True, null=True, related_name='games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='moves',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='white',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='w', to=settings.AUTH_USER_MODEL),
        ),
    ]
