# Generated by Django 4.1.7 on 2023-03-23 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friend', '0007_alter_gamelist_black_alter_gamelist_games_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelist',
            name='black',
        ),
        migrations.RemoveField(
            model_name='gamelist',
            name='white',
        ),
        migrations.AddField(
            model_name='gamelist',
            name='black',
            field=models.ManyToManyField(null=True, related_name='b', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamelist',
            name='white',
            field=models.ManyToManyField(null=True, related_name='w', to=settings.AUTH_USER_MODEL),
        ),
    ]
