# Generated by Django 4.1.7 on 2023-03-23 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friend', '0008_remove_gamelist_black_remove_gamelist_white_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelist',
            name='games',
        ),
        migrations.RemoveField(
            model_name='gamelist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gamelist',
            name='black',
        ),
        migrations.RemoveField(
            model_name='gamelist',
            name='white',
        ),
        migrations.AddField(
            model_name='gamelist',
            name='black',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamelist',
            name='white',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='w', to=settings.AUTH_USER_MODEL),
        ),
    ]
