# Generated by Django 4.1.7 on 2023-03-23 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friend', '0011_alter_gamelist_moves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='black',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='turn',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gamelist',
            name='white',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='w', to=settings.AUTH_USER_MODEL),
        ),
    ]
